// Mock data layer — fixtures used until the backend is live.
// Themed around GuestMatchr (podcast guest–host matching) so tickets read real.
import type { Category, Employee, Ticket } from "@/types";

export const mockEmployees: Employee[] = [
  { id: 1, name: "Soham", email: "soham@guestmatchr.dev", role: "agent", designation: "Product" },
  { id: 2, name: "Parinita", email: "parinita@guestmatchr.dev", role: "developer", designation: "Frontend Dev" },
  { id: 3, name: "Aditya", email: "aditya@guestmatchr.dev", role: "developer", designation: "Backend Dev" },
  { id: 4, name: "Meera", email: "meera@guestmatchr.dev", role: "developer", designation: "Full-stack Dev" },
];

export const mockCategories: Category[] = [
  { category_id: 1, name: "Backend" },
  { category_id: 2, name: "Frontend" },
  { category_id: 3, name: "Auth" },
  { category_id: 4, name: "Database" },
  { category_id: 5, name: "Infra" },
];

export const mockTickets: Ticket[] = [
  {
    ticket_id: 101,
    name: "Guest match scores render as NaN",
    description: "Compatibility score column shows NaN when a guest has no past episodes.",
    category_id: 2,
    status: "todo",
    priority: "urgent",
    assigned_to: 2,
    time_to_complete: "3h",
    created_at: "2026-07-10T09:15:00Z",
  },
  {
    ticket_id: 102,
    name: "Login rejects valid host credentials",
    description: "JWT verification fails for hosts created before the schema migration.",
    category_id: 3,
    status: "doing",
    priority: "severe",
    assigned_to: 3,
    time_to_complete: "1d",
    created_at: "2026-07-09T14:02:00Z",
  },
  {
    ticket_id: 103,
    name: "Episode booking emails not queued",
    description: "Booking confirmation is created but never picked up by the worker.",
    category_id: 1,
    status: "todo",
    priority: "normal",
    assigned_to: null,
    time_to_complete: "4h",
    created_at: "2026-07-11T11:30:00Z",
  },
  {
    ticket_id: 104,
    name: "Search index missing new guest tags",
    description: "Newly added topic tags don't appear in guest search for ~10 min.",
    category_id: 4,
    status: "doing",
    priority: "urgent",
    assigned_to: 2,
    time_to_complete: "6h",
    created_at: "2026-07-08T16:45:00Z",
  },
  {
    ticket_id: 105,
    name: "Calendar timezone off by one hour",
    description: "Availability slots shift by an hour for hosts in DST regions.",
    category_id: 2,
    status: "todo",
    priority: "normal",
    assigned_to: 4,
    time_to_complete: "5h",
    created_at: "2026-07-12T08:20:00Z",
  },
  {
    ticket_id: 106,
    name: "Rate limit blocks legitimate match refresh",
    description: "Refreshing matches more than 3x/min returns 429 for power users.",
    category_id: 5,
    status: "done",
    priority: "normal",
    assigned_to: 3,
    time_to_complete: "2h",
    created_at: "2026-07-06T10:05:00Z",
  },
  {
    ticket_id: 107,
    name: "Profile avatar upload fails over 2MB",
    description: "Uploads above 2MB silently fail with no error to the user.",
    category_id: 1,
    status: "done",
    priority: "urgent",
    assigned_to: 2,
    time_to_complete: "3h",
    created_at: "2026-07-05T13:40:00Z",
  },
  {
    ticket_id: 108,
    name: "Dashboard crashes with zero matches",
    description: "Empty match list throws instead of showing the empty state.",
    category_id: 2,
    status: "todo",
    priority: "severe",
    assigned_to: 4,
    time_to_complete: "2h",
    created_at: "2026-07-13T07:10:00Z",
  },
];
